#!/usr/bin/env sh
path=`dirname $0`
cd $path

truffle compile && echo compiling...
echo
truffle migrate && echo migrate our constract to internet... 
echo 

# echo
# echo run app server...
# npm run dev
